# Generated by Django 3.1.3 on 2020-11-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20201128_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppingamount',
            name='toppings',
        ),
        migrations.AddField(
            model_name='toppingamount',
            name='toppings',
            field=models.ManyToManyField(related_name='topping_amounts', to='pizzas.Topping'),
        ),
    ]
