# Generated by Django 3.1.3 on 2020-12-07 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0002_auto_20201205_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToppingAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(choices=[(1, 'Regular'), (2, 'Double'), (3, 'Triple')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='pizzas',
            name='amount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meal_plans.toppingamount'),
            preserve_default=False,
        ),
    ]
